EXECUTABLE	:= gc
CUFILES		:= graphColoring.cu
CCFILES		:= graphDriver.cpp
#	imageWrite.cpp
	
#CU_DEPS := CudaCuts.cu edgeWeight.cu PushRelabel_kernel.cu Bfs_kernel.cu
SMVERSIONFLAGS  := -arch sm_20
#SMVERSIONFLAGS  := -arch sm_12

include ../../common/common.mk
