EXECUTABLE	:= maximal_independent_set
CUFILES_sm_20	:= maximal_independent_set.cu
CCFILES		:= /
#	imageWrite.cpp
	
#CU_DEPS := CudaCuts.cu edgeWeight.cu PushRelabel_kernel.cu Bfs_kernel.cu
#SMVERSIONFLAGS  := -arch sm_20
#SMVERSIONFLAGS  := -arch sm_12

include ../../common/common.mk
